// ============================================================================
// Textos de UI del MVP (es-MX). Regla i18n del proyecto: los textos viven en
// módulos de contenido como este, nunca cableados en JSX profundo — cambiar
// de idioma es cambiar de módulo, no cazar cadenas.
// ============================================================================

export const content = {
  home: {
    title: 'LomitoDeVuelta 🐕',
    tagline: 'Sube una foto y la IA busca por ti.',
  },
  flowB: {
    heading: 'Encontré un perro',
    photoLabel: 'Foto del perro (una basta)',
    locationLabel: 'Ubicación donde lo encontraste',
    useMyLocation: 'Usar mi ubicación actual',
    locationCaptured: 'Ubicación capturada',
    locationError: 'No pudimos obtener tu ubicación. Activa el GPS y vuelve a intentar.',
    dateLabel: '¿Cuándo lo encontraste?',
    noteLabel: '¿Dónde está el perro ahora? (opcional)',
    notePlaceholder: 'Ej. "Lo tengo en mi casa" o "Sigue en el parque de la esquina"',
    whatsappLabel: 'Tu WhatsApp (para avisarte si aparece su familia)',
    whatsappPlaceholder: '+52 55 1234 5678',
    consentLabel:
      'Acepto que mi contacto se use únicamente para conectarme si hay coincidencia, y que la foto y la ubicación aproximada se muestren públicamente.',
    privacyLink: 'Aviso de privacidad',
    submit: 'Buscar a su familia',
    stages: {
      compressing: 'Preparando la foto…',
      uploading: 'Subiendo la foto…',
      analyzing: 'La IA está analizando la foto…',
      searching: 'Buscando perros perdidos cerca de ti…',
    },
    errors: {
      missingPhoto: 'Necesitamos al menos una foto.',
      missingLocation: 'Necesitamos la ubicación para buscar cerca.',
      missingConsent: 'Necesitamos tu consentimiento para crear el reporte.',
      generic: 'Algo salió mal. Tu foto no se perdió: intenta de nuevo.',
    },
  },
  flowA: {
    heading: 'Perdí a mi perro',
    homeLink: '¿Perdiste a tu perro? Repórtalo aquí',
    photosLabel: 'Fotos de tu perro (1 a 5; la primera es la principal)',
    tooManyPhotos: 'Máximo 5 fotos.',
    locationLabel: '¿Dónde se perdió?',
    dateLabel: '¿Cuándo se perdió?',
    marksLabel: 'Señas particulares (opcional — la IA también detecta algunas)',
    marksPlaceholder: 'Ej. "mancha blanca en el pecho, collar rojo"',
    submit: 'Crear reporte y buscar',
    editHeading: 'Revisa la ficha que armó la IA',
    editBody: 'Corrige lo que no coincida: tu corrección siempre gana.',
  },
  editor: {
    breedMix: 'Raza(s), separadas por coma',
    colors: 'Colores, separados por coma',
    size: 'Tamaño',
    sex: 'Sexo',
    sexConfirmedHint: 'Al elegir el sexo confirmas que lo sabes de cierto.',
    ageRange: 'Edad',
    coatLength: 'Pelo',
    distinctiveMarks: 'Señas particulares',
    unknown: '(no sé)',
    save: 'Guardar corrección',
    saved: 'Guardado ✓',
    saveError: 'No se pudo guardar. Intenta de nuevo.',
    options: {
      size: { small: 'chico', medium: 'mediano', large: 'grande' },
      sex: { male: 'macho', female: 'hembra' },
      ageRange: { puppy: 'cachorro', young: 'joven', adult: 'adulto', senior: 'senior' },
      coatLength: { short: 'corto', medium: 'mediano', long: 'largo' },
    } as Record<string, Record<string, string>>,
  },
  manage: {
    heading: 'Gestionar tu reporte',
    invalidTitle: 'Enlace de gestión inválido',
    invalidBody:
      'El enlace no corresponde a ningún reporte activo. Si perdiste tu enlace, se te puede reenviar al MISMO WhatsApp con el que creaste el reporte.',
    statusLabel: 'Estado',
    statusValues: {
      active: 'activo',
      reunited: 'reunido 🎉',
      expired: 'expirado',
      removed: 'retirado',
    } as Record<string, string>,
    expiresLabel: 'Vigente hasta',
    viewFicha: 'Ver la ficha pública',
    editHeading: 'Corregir la ficha',
    renewHeading: 'Renovar vigencia',
    renewBody: 'Extiende tu reporte 60 días más a partir de hoy.',
    renewButton: 'Renovar 60 días',
    renewed: (date: string) => `Renovado: vigente hasta ${date} ✓`,
    renewError: 'No se pudo renovar. Intenta de nuevo.',
    deleteHeading: 'Borrar el reporte',
    deleteBody:
      'El reporte deja de ser visible de inmediato y tus datos personales se purgan de forma definitiva en el siguiente ciclo programado (LFPDPPP).',
    deleteConfirm: '¿Seguro? Esta acción no se puede deshacer.',
    deleteButton: 'Borrar mi reporte',
    deleted: 'Reporte borrado. Gracias por usar LomitoDeVuelta.',
    deleteError: 'No se pudo borrar. Intenta de nuevo.',
  },
  ficha: {
    lostBadge: 'PERDIDO',
    foundBadge: 'ENCONTRADO',
    lostHeading: 'Se busca a este perro',
    foundHeading: 'Este perro fue encontrado',
    eventDateLost: 'Se perdió el',
    eventDateFound: 'Encontrado el',
    nearLabel: 'Cerca de',
    marksLabel: 'Señas particulares',
    rewardBadge: '🎁 Ofrece recompensa',
    sensitiveWarning: 'Imagen sensible: el perro podría verse herido.',
    tapToReveal: 'Toca para ver',
    shareButton: 'Compartir por WhatsApp',
    shareText: (badge: string) => `${badge} 🐕 Ayúdalo a volver con su familia:`,
    ctaLost: '¿Lo encontraste tú? Repórtalo aquí',
    ctaFound: '¿Es tu perro? Crea tu reporte para conectar',
    cta: 'Ayúdalo a volver 🐾',
    notFoundTitle: 'Este reporte ya no está disponible',
    notFoundBody: 'Puede haber expirado, haberse retirado, o el enlace es incorrecto.',
    attributeLabels: {
      breedMix: 'Raza',
      colors: 'Colores',
      size: 'Tamaño',
      sex: 'Sexo',
      ageRange: 'Edad',
      coatLength: 'Pelo',
    } as Record<string, string>,
    attributeValues: {
      small: 'chico',
      medium: 'mediano',
      large: 'grande',
      male: 'macho',
      female: 'hembra',
      puppy: 'cachorro',
      young: 'joven',
      adult: 'adulto',
      senior: 'senior',
      short: 'corto',
      long: 'largo',
    } as Record<string, string>,
  },
  results: {
    candidatesHeading: 'Posibles coincidencias cerca de ti',
    noCandidatesHeading: 'Tu reporte quedó registrado',
    noCandidatesBody:
      'Aún no hay reportes que coincidan. El sistema seguirá buscando solo y te avisará por WhatsApp si aparece una familia buscando a este perro.',
    manageLinkHeading: 'Guarda tu enlace de gestión',
    manageLinkBody:
      'Con este enlace puedes editar o cerrar tu reporte. Te lo enviamos también por WhatsApp. Se muestra UNA sola vez:',
    copyLink: 'Copiar enlace',
    copied: '¡Copiado!',
    ambiguityWarning: 'Hay varios perros parecidos en la zona — revisa las señas particulares.',
    contactMasked: 'Contacto',
    bandLabels: {
      muy_alta: 'Coincidencia muy alta',
      alta: 'Coincidencia alta',
      posible: 'Posible coincidencia',
    } as Record<string, string>,
  },
} as const;
